import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { BookmarkDataProvider } from "@/context/BookmarkDataContext";
import { BookmarkUIProvider } from "@/context/BookmarkUIContext";
import { Header } from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <BookmarkDataProvider>
            <BookmarkUIProvider>
              <Header />
              {children}
            </BookmarkUIProvider>
          </BookmarkDataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
